### PR TITLE
Latency optimization feature for single light source

### PR DESCRIPTION
**Pull request by bradleydworak**
This change simplifies the averaging algorithm and significantly reduces latency for use with a single light source.

### CODE REVIEW

**Comment by MCPCapital** [comment]
Thanks for taking the lead on this @bradleydworak ! 
I have invited you as a collaborator if you would like to be able to pull these in yourself :)

**Comment by bradleydworak** [comment]
Hey Matthew,

Thanks for the invite. I clicked on the invitation and it said the
invitation expired, not sure why. Can you retry? Also would be great if I
could be allowed to add release versions. Wanted to bump this up to 1.2.0.

By the way, I have a Philips Hue light strip that has 7 individual light
segments. I don't know how to address the segments individually. Do you
know if this can be figured out or who may be able to help? Would be great
to get this working.

Brad

**Comment by MCPCapital** [comment]
Hey Brad! Just sent you a new invite! Feel free to merge stuff in, issue releases, etc.  :)

Its been a while since I've looked at this stuff - when this was made they didnt have individually addressable segments in the light strips, so I am not really sure. Ares and I have moved onto another venture and we don't have the time to dive back into this at the moment. You probably have, but I'd check the official docs. Most of what was created here was based on those docs plus a little reverse engineering.

Also glad to see you gave yourself credit, it is well-deserved :)

**Comment by bradleydworak** [comment]
Hi Matthew,

Hope you’re doing well.

What model lights, and how many, did you guys test in your configuration? I
would like to include on the Readme which ones have been tested so far.

Cheers,

Brad

**Comment by MCPCapital** [comment]
Hey Brad!

The scripts were originally developed using 3 hue color bulbs (Gen2 I think). Over time I collected more lights though and the final setup I used consisted of 10 Play Bars mounted on the back of the TV. At the time, 10 was the maximum number of lights for an entertainment area - not sure if this has changed since.

Thanks for continuing to tend to this!

Cheers,
Matthew

**Pull request merged**
